<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\RoadmapAction;

class RoadmapActionSeeder extends Seeder
{
    public function run(): void
    {
        $actions = [
            // ================= JANGKA PENDEK (TAHUN 1 - 2) =================
            [
                'program_name' => 'Integrasi Sistem Informasi Pelaporan Timbulan Limbah B3 Medis Fasyankes Nasional (SIMPEL - SIKER)',
                'baseline' => 'Cakupan pelaporan fasyankes nasional baru mencapai 34%',
                'target' => 'Cakupan pelaporan terintegrasi mencapai 80% seluruh Fasyankes',
                'priority_location' => 'Nasional (Seluruh Provinsi)',
                'time_horizon' => 'Jangka Pendek (Tahun 1-2)',
                'responsible_agency' => 'KLH / BPLH',
                'supporting_agency' => 'Kementerian Kesehatan, Dinas Lingkungan Hidup Daerah',
                'indicative_budget' => 12500000000,
                'kpi' => 'Persentase Fasyankes yang melaporkan manifes digital secara berkala',
                'program_output' => 'Modul interoperabilitas data Fasyankes nasional aktif',
                'funding_source' => 'DIPA KLH & PHLN',
                'progress_percent' => 45,
            ],
            [
                'program_name' => 'Program Akselerasi Perizinan TPS Limbah B3 Fasyankes Terakreditasi (Quick Wins)',
                'baseline' => '52% Puskesmas dan RS Daerah belum memiliki persetujuan teknis / rincian teknis TPS B3',
                'target' => 'Peningkatan legalitas TPS B3 Fasyankes menjadi 85%',
                'priority_location' => 'Pulau Jawa, Sumatera, dan Sulawesi',
                'time_horizon' => 'Jangka Pendek (Tahun 1-2)',
                'responsible_agency' => 'Dinas Lingkungan Hidup Provinsi / Kabupaten / Kota',
                'supporting_agency' => 'KLH / BPLH, Kementerian Kesehatan',
                'indicative_budget' => 8000000000,
                'kpi' => 'Jumlah Rincian Teknis TPS Limbah B3 yang diterbitkan Pemda',
                'program_output' => 'Pedoman bimtek standar dan 5.000 Fasyankes terverifikasi izin',
                'funding_source' => 'APBD & DAK Non-Fisik Lingkungan',
                'progress_percent' => 30,
            ],
            [
                'program_name' => 'Penetapan Standar dan Verifikasi 50 Titik Pilot Lokasi Pemindahan Berfasilitas Cold Storage',
                'baseline' => 'Keterbatasan cold storage menyebabkan limbah medis tersimpan melebihi batas 2x24 jam',
                'target' => '50 Lokasi Pemindahan regional percontohan dilengkapi cold storage terstandardisasi',
                'priority_location' => 'Wilayah Kepulauan (Maluku, NTT, Kepri, Bangka Belitung)',
                'time_horizon' => 'Jangka Pendek (Tahun 1-2)',
                'responsible_agency' => 'KLH / BPLH',
                'supporting_agency' => 'Pemerintah Daerah, Asosiasi Pengolah Limbah B3',
                'indicative_budget' => 35000000000,
                'kpi' => 'Rasio kepatuhan waktu simpan limbah infeksius di wilayah kepulauan',
                'program_output' => '50 cold storage berizin dengan kapasitas minimal 5 ton/unit',
                'funding_source' => 'APBN KLH & Hibah Internasional',
                'progress_percent' => 20,
            ],
            [
                'program_name' => 'Penguatan Regulasi Rute dan Konsolidasi Transporter Berizin Antar-Pulau',
                'baseline' => 'Biaya logistik angkut limbah medis dari pulau terluar ke Jawa mencapai Rp 35.000/kg',
                'target' => 'Efisiensi tarif angkut limbah antar-pulau turun minimal 30% dengan skema trayek reguler',
                'priority_location' => 'Koridor Laut Maluku - Surabaya dan Papua - Makassar',
                'time_horizon' => 'Jangka Pendek (Tahun 1-2)',
                'responsible_agency' => 'Kementerian Perhubungan',
                'supporting_agency' => 'KLH / BPLH, Pelindo, Asosiasi Transporter Limbah B3',
                'indicative_budget' => 6500000000,
                'kpi' => 'Frekuensi kapal pengangkut limbah B3 medis terjadwal',
                'program_output' => 'SK Bersama Menhub - MenLH tentang Trayek Khusus Angkutan Laut B3 Medis',
                'funding_source' => 'APBN Kemenhub / KLH',
                'progress_percent' => 25,
            ],
            [
                'program_name' => 'Kompilasi dan Pemutakhiran Neraca Geospasial Limbah B3 Medis Berbasis AI & GIS',
                'baseline' => 'Peta sebaran masih bersifat parsial dan belum real-time',
                'target' => 'Platform WebGIS Nasional operasional dengan update data per semester',
                'priority_location' => 'Nasional',
                'time_horizon' => 'Jangka Pendek (Tahun 1-2)',
                'responsible_agency' => 'KLH / BPLH',
                'supporting_agency' => 'Badan Informasi Geospasial (BIG), BRIN',
                'indicative_budget' => 4500000000,
                'kpi' => 'Ketersediaan peta gap kapasitas dan buffer layanan 38 provinsi',
                'program_output' => 'Aplikasi WebGIS Nasional Terverifikasi',
                'funding_source' => 'DIPA KLH 2026',
                'progress_percent' => 60,
            ],

            // ================= JANGKA MENENGAH (TAHUN 3 - 5) =================
            [
                'program_name' => 'Pembangunan Fasilitas Pengolah Insinerator / Autoklaf Skala Regional di Kawasan Timur Indonesia',
                'baseline' => 'Wilayah Papua, Maluku, dan Nusa Tenggara Timur mengalami defisit kapasitas > 60%',
                'target' => 'Terbangunnya 6 unit fasilitas pengolahan regional berkapasitas total 30 ton/hari',
                'priority_location' => 'Kupang (NTT), Ambon (Maluku), Jayapura (Papua), Manokwari (Papua Barat)',
                'time_horizon' => 'Jangka Menengah (Tahun 3-5)',
                'responsible_agency' => 'KLH / BPLH',
                'supporting_agency' => 'Pemerintah Provinsi, Badan Usaha Milik Daerah (BUMD)',
                'indicative_budget' => 180000000000,
                'kpi' => 'Penurunan angka defisit pengolahan limbah medis KTI di bawah 20%',
                'program_output' => '6 fasilitas pengolahan regional tersertifikasi baku mutu emisi',
                'funding_source' => 'SBSN, KPBU, & APBN',
                'progress_percent' => 10,
            ],
            [
                'program_name' => 'Optimalisasi dan Peningkatan Kapasitas Autoklaf Non-Insinerasi pada Rumah Sakit Tipe B dan C',
                'baseline' => 'Hanya 8% RS yang memiliki fasilitas pengolahan mandiri berizin ramah lingkungan',
                'target' => '200 RS Daerah mengoperasikan autoklaf berizin mandiri untuk limbah infeksius',
                'priority_location' => 'Sumatera, Kalimantan, dan Sulawesi',
                'time_horizon' => 'Jangka Menengah (Tahun 3-5)',
                'responsible_agency' => 'Kementerian Kesehatan',
                'supporting_agency' => 'KLH / BPLH, Asosiasi Rumah Sakit (PERSI)',
                'indicative_budget' => 120000000000,
                'kpi' => 'Persentase limbah medis yang diolah on-site pada fasyankes',
                'program_output' => '200 unit autoklaf terpasang dengan pemantauan parameter spore strip rutin',
                'funding_source' => 'DAK Fisik Kesehatan & BLU Fasyankes',
                'progress_percent' => 5,
            ],
            [
                'program_name' => 'Pengembangan Sistem Pengumpulan dan Distribusi Terpadu Berbasis Hub-and-Spoke',
                'baseline' => 'Puskesmas remote mengalami penumpukan limbah tajam dan patologis',
                'target' => '100% Puskesmas terlayani pengangkutan terjadwal maksimal setiap 14 hari',
                'priority_location' => 'Jawa Timur, Jawa Tengah, Lampung, Sulawesi Selatan',
                'time_horizon' => 'Jangka Menengah (Tahun 3-5)',
                'responsible_agency' => 'Pemerintah Kabupaten / Kota (Dinas Kesehatan & DLH)',
                'supporting_agency' => 'Pengelola Fasilitas B3 Komersial',
                'indicative_budget' => 45000000000,
                'kpi' => 'Cakupan layanan fasyankes tingkat primer di daerah rural',
                'program_output' => 'Kontrak payung regional pengangkutan limbah fasyankes primer',
                'funding_source' => 'APBD & BOK Puskesmas',
                'progress_percent' => 10,
            ],
            [
                'program_name' => 'Penguatan Pengawasan dan Kepatuhan Baku Mutu Emisi Insinerator Berkelanjutan',
                'baseline' => 'Pemantauan dioksin/furan masih terkendala ketersediaan laboratorium terakreditasi',
                'target' => '100% fasilitas pengolahan komersial dan mandiri teruji dioksin/furan tahunan',
                'priority_location' => 'Nasional',
                'time_horizon' => 'Jangka Menengah (Tahun 3-5)',
                'responsible_agency' => 'KLH / BPLH',
                'supporting_agency' => 'Laboratorium Rujukan Lingkungan Terakreditasi KAN',
                'indicative_budget' => 18000000000,
                'kpi' => 'Tingkat kepatuhan emisi cerobong terhadap PermenLHK P.56/2015',
                'program_output' => 'Laporan audit lingkungan berkala dan sistem CEMS terintegrasi',
                'funding_source' => 'DIPA KLH',
                'progress_percent' => 15,
            ],
            [
                'program_name' => 'Penyediaan Insentif Finansial & Fiskal untuk Investasi Fasilitas Pengolahan B3 Hijau',
                'baseline' => 'Minat investasi swasta terkonsentrasi di Pulau Jawa (>75%)',
                'target' => 'Realisasi investasi swasta/BUMD pengolah limbah B3 di Luar Jawa meningkat 50%',
                'priority_location' => 'Kalimantan, Sulawesi, dan Maluku-Papua',
                'time_horizon' => 'Jangka Menengah (Tahun 3-5)',
                'responsible_agency' => 'Kementerian Investasi / BKPM & Kemenkeu',
                'supporting_agency' => 'KLH / BPLH',
                'indicative_budget' => 5000000000,
                'kpi' => 'Jumlah nilai investasi pengolahan limbah B3 medis di luar Jawa',
                'program_output' => 'Paket kemudahan perizinan terintegrasi OSS dan tax allowance fasilitas ramah lingkungan',
                'funding_source' => 'APBN Reguler',
                'progress_percent' => 5,
            ],

            // ================= JANGKA PANJANG (TAHUN 6 - 10) =================
            [
                'program_name' => 'Pencapaian Nol Wilayah Defisit Kritis Nasional (Zero Deficit Capacity)',
                'baseline' => '14 dari 38 provinsi berstatus defisit kritis pengolahan pada baseline 2026',
                'target' => 'Seluruh 38 provinsi mencapai rasio kapasitas terhadap timbulan minimal 100%',
                'priority_location' => 'Nasional (Seluruh Wilayah Indonesia)',
                'time_horizon' => 'Jangka Panjang (Tahun 6-10)',
                'responsible_agency' => 'KLH / BPLH',
                'supporting_agency' => 'Kemenkes, Kemendagri, Seluruh Pemerintah Provinsi',
                'indicative_budget' => 250000000000,
                'kpi' => 'Jumlah provinsi dengan status Defisit Kritis = 0',
                'program_output' => 'Kemakmuran rantai pasok pengolahan medis merata secara spasial',
                'funding_source' => 'Multi-funding (APBN, APBD, Swasta, Sindikasi Perbankan Hijau)',
                'progress_percent' => 0,
            ],
            [
                'program_name' => 'Transisi Sirkular Ekonomi dan Dekarbonisasi Pengelolaan Residu Abu Insinerator (Bottom Ash & Fly Ash)',
                'baseline' => 'Sebagian besar fly ash dan bottom ash ditimbun di landfill B3 kelas I/II tanpa pemanfaatan',
                'target' => '40% residu abu insinerator termanfaatkan aman sebagai substitusi bahan bangunan (paving/batako B3 aman)',
                'priority_location' => 'Sentra Pengolahan Jawa dan Sumatera',
                'time_horizon' => 'Jangka Panjang (Tahun 6-10)',
                'responsible_agency' => 'KLH / BPLH',
                'supporting_agency' => 'Kementerian PU, Asosiasi Semen Indonesia, Industri Material Konstruksi',
                'indicative_budget' => 30000000000,
                'kpi' => 'Volume residu abu B3 medis yang mendapatkan izin pemanfaatan resmi',
                'program_output' => 'Standardisasi teknis produk paving block/material turunan ramah lingkungan',
                'funding_source' => 'R&D BUMN / Swasta & LPDP',
                'progress_percent' => 0,
            ],
            [
                'program_name' => 'Implementasi Total Tracking Digital Terintegrasi GPS & Barcode RFID Rantai Pasok Limbah Medis',
                'baseline' => 'Manifest masih menggunakan pelaporan pasif SIMPEL/Festronik',
                'target' => '100% armada transporter dan kemasan limbah medis terlacak real-time via satelit dan IoT',
                'priority_location' => 'Nasional',
                'time_horizon' => 'Jangka Panjang (Tahun 6-10)',
                'responsible_agency' => 'KLH / BPLH',
                'supporting_agency' => 'Kementerian Kominfo, Korlantas Polri, Asosiasi Pengusaha B3',
                'indicative_budget' => 20000000000,
                'kpi' => 'Tingkat kepatuhan rute pengangkutan dan penanganan tumpahan di perjalanan (spill response)',
                'program_output' => 'Pusat komando pengendali limbah B3 medis nasional (Command Center KLH)',
                'funding_source' => 'APBN & PNBP KLH',
                'progress_percent' => 0,
            ],
            [
                'program_name' => 'Pembangunan Fasilitas Pengolahan Limbah Medis Berteknologi Tinggi (Plasma Gasification / Thermal Non-Incineration)',
                'baseline' => 'Teknologi didominasi pembakaran konvensional suhu tinggi 800 - 1200 °C',
                'target' => 'Pengoperasian 2 unit fasilitas percontohan gasifikasi plasma tanpa emisi dioksin',
                'priority_location' => 'Kawasan Megapolitan Jabodetabek dan Gerbangkertosusila',
                'time_horizon' => 'Jangka Panjang (Tahun 6-10)',
                'responsible_agency' => 'KLH / BPLH & BRIN',
                'supporting_agency' => 'Kementerian ESDM, Pemprov DKI Jakarta & Jatim',
                'indicative_budget' => 300000000000,
                'kpi' => 'Pelepasan emisi karbon per kg limbah terolah berkurang drastis',
                'program_output' => '2 unit plasma gasifikasi mandiri energi menghasilkan syn-gas bersih',
                'funding_source' => 'Kerjasama Internasional GCF (Green Climate Fund) & Swasta',
                'progress_percent' => 0,
            ],
            [
                'program_name' => 'Penguatan Ketahanan Sistem Pengelolaan Limbah Medis Saat Krisis Kesehatan & Bencana Alam',
                'baseline' => 'Lonjakan timbulan limbah 3x lipat saat krisis pandemi/bencana kerap melumpuhkan sistem lokal',
                'target' => 'Prosedur darurat nasional teruji dengan unit insinerator mobile siap diterjunkan dalam 24 jam',
                'priority_location' => 'Wilayah Rawan Bencana (Ring of Fire)',
                'time_horizon' => 'Jangka Panjang (Tahun 6-10)',
                'responsible_agency' => 'BNPB & KLH / BPLH',
                'supporting_agency' => 'Kementerian Kesehatan, TNI / Polri',
                'indicative_budget' => 40000000000,
                'kpi' => 'Waktu tanggap darurat penanganan limbah medis pasca-bencana',
                'program_output' => '10 unit insinerator bergerak (mobile treatment containerized) siaga regional',
                'funding_source' => 'Dana Siap Pakai BNPB & APBN',
                'progress_percent' => 0,
            ],
        ];

        foreach ($actions as $action) {
            RoadmapAction::create($action);
        }
    }
}
